remote_theme: fluffyemily/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'typescript-fun on GitHub':
    - 'https://typescript.fun'
